# Generated by Django 3.1.8 on 2023-04-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SP_U', models.FloatField()),
                ('RA_AMP_U', models.FloatField()),
                ('LA_AMP_U', models.FloatField()),
                ('RA_STD_U', models.FloatField()),
                ('LA_STD_U', models.FloatField()),
                ('SYM_U', models.FloatField()),
                ('R_JERK_U', models.FloatField()),
                ('L_JERK_U', models.FloatField()),
                ('ASA_U', models.FloatField()),
                ('ASYM_IND_U', models.FloatField()),
                ('TRA_U', models.FloatField()),
                ('T_AMP_U', models.FloatField()),
                ('CAD_U', models.FloatField()),
                ('STR_T_U', models.FloatField()),
                ('STR_CV_U', models.FloatField()),
                ('STEP_REG_U', models.FloatField()),
                ('STEP_SYM_U', models.FloatField()),
                ('JERK_T_U', models.FloatField()),
                ('SP_DT', models.FloatField()),
                ('RA_AMP_DT', models.FloatField()),
                ('LA_AMP_DT', models.FloatField()),
                ('RA_STD_DT', models.FloatField()),
                ('LA_STD_DT', models.FloatField()),
                ('SYM_DT', models.FloatField()),
                ('R_JERK_DT', models.FloatField()),
                ('L_JERK_DT', models.FloatField()),
                ('ASA_DT', models.FloatField()),
                ('ASYM_IND_DT', models.FloatField()),
                ('TRA_DT', models.FloatField()),
                ('T_AMP_DT', models.FloatField()),
                ('CAD_DT', models.FloatField()),
                ('STR_T_DT', models.FloatField()),
                ('STR_CV_DT', models.FloatField()),
                ('STEP_REG_DT', models.FloatField()),
                ('STEP_SYM_DT', models.FloatField()),
                ('JERK_T_DT', models.FloatField()),
                ('SW_VEL_OP', models.FloatField()),
                ('SW_PATH_OP', models.FloatField()),
                ('SW_FREQ_OP', models.FloatField()),
                ('SW_JERK_OP', models.FloatField()),
                ('SW_VEL_CL', models.FloatField()),
                ('SW_PATH_CL', models.FloatField()),
                ('SW_FREQ_CL', models.FloatField()),
                ('SW_JERK_CL', models.FloatField()),
                ('TUG1_DUR', models.FloatField()),
                ('TUG1_STEP_NUM', models.FloatField()),
                ('TUG1_STRAIGHT_DUR', models.FloatField()),
                ('TUG1_TURNS_DUR', models.FloatField()),
                ('TUG1_STEP_REG', models.FloatField()),
                ('TUG1_STEP_SYM', models.FloatField()),
                ('TUG2_DUR', models.FloatField()),
                ('TUG2_STEP_NUM', models.FloatField()),
                ('TUG2_STRAIGHT_DUR', models.FloatField()),
                ('TUG2_TURNS_DUR', models.FloatField()),
                ('TUG2_STEP_REG', models.FloatField()),
                ('TUG2_STEP_SYM', models.FloatField()),
            ],
        ),
    ]
